apiVersion: v1
stringData:
  name: romisek-cn
  password: github_pat_
  project: cn
  type: git
  url: https://github.com/Romanecek/argo-clusterResourceWhitelist-test.git
  username: Romanecek
  forceHttpBasicAuth: "true"
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: romisek-repo-cn
  namespace: cn-data-plane-system
type: Opaque
---
apiVersion: v1
stringData:
  name: romisek-custom-domains
  password: github_pat_
  project: custom-domains
  type: git
  url: https://github.com/Romanecek/argo-clusterResourceWhitelist-test.git
  forceHttpBasicAuth:  "true"
  username: Romanecek
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: romisek-repo-custom-domains
  namespace: cn-data-plane-system
type: Opaque
---
apiVersion: v1
stringData:
  name: romisek-default
  password: github_pat_
  project: default
  type: git
  url: https://github.com/Romanecek/argo-clusterResourceWhitelist-test.git
  username: Romanecek
  forceHttpBasicAuth:  "true"
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: romisek-repo-default
  namespace: cn-data-plane-system
type: Opaque