apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: necum
spec:
  params:
  - name: username
    type: string
  steps:
    - name: say-hello
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        echo "Hello $(params.username)!"   