apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
spec:
  hosts:
  - test.test
  http:
  - name: "cccc"
    match:
    - uri:
        prefix: "/ccc"
    rewrite:
      uri: "/ccc"
    route:
    - destination:
        host: test
        subset: v2