apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data: 
  hovno: "prdel"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: kube-system
data: 
  hovno: "prdel"