apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: customer-hijack-proj
  namespace: cn-data-plane-system
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
status: {}