apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: environment-test
  namespace: cn-data-plane-system
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: cn
  source:
    path: envs/test
    repoURL: https://github.com/Romanecek/argo-clusterResourceWhitelist-test.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true